// <auto-generated />
using ConsoleApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleApp.Migrations
{
    [DbContext(typeof(ConsoleStudentContext))]
    partial class ConsoleStudentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClassLibrary.Course", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LecturerID")
                        .HasColumnType("int");

                    b.Property<int>("QQILevel")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("LecturerID");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CourseName = "Introduction to Programming",
                            Description = "blah blah for loop",
                            LecturerID = 2,
                            QQILevel = 6
                        },
                        new
                        {
                            ID = 2,
                            CourseName = "Advanced Databases",
                            Description = "Relational DBs are superior",
                            LecturerID = 1,
                            QQILevel = 7
                        },
                        new
                        {
                            ID = 3,
                            CourseName = "Functional Programming",
                            Description = "blah blah for loop",
                            LecturerID = 2,
                            QQILevel = 6
                        });
                });

            modelBuilder.Entity("ClassLibrary.Lecturer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Lecturers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "otto@atu.ie",
                            FirstName = "Otto",
                            Surname = "Octavius",
                            Title = "Dr."
                        },
                        new
                        {
                            ID = 2,
                            Email = "dominic.carr@atu.ie",
                            FirstName = "Dominic",
                            Surname = "Carr",
                            Title = "Dr."
                        });
                });

            modelBuilder.Entity("ClassLibrary.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Eircode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Age = 22,
                            Eircode = "A94 FP71",
                            Email = "jammyboi@yahoo.com",
                            FirstName = "James",
                            Surname = "Johnson"
                        },
                        new
                        {
                            ID = 2,
                            Age = 45,
                            Eircode = "D14 X3H0",
                            Email = "spider-man@marvel.com",
                            FirstName = "Peter",
                            Surname = "Parker"
                        },
                        new
                        {
                            ID = 3,
                            Age = 78,
                            Eircode = "D07 Y3B0",
                            Email = "thedonald45@usa.com",
                            FirstName = "Donald",
                            Surname = "Trump"
                        },
                        new
                        {
                            ID = 4,
                            Age = 22,
                            Eircode = "A84 FP91",
                            Email = "jacky@yahoo.com",
                            FirstName = "Jack",
                            Surname = "O'Hagan"
                        });
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.Property<int>("CoursesID")
                        .HasColumnType("int");

                    b.Property<int>("StudentsID")
                        .HasColumnType("int");

                    b.HasKey("CoursesID", "StudentsID");

                    b.HasIndex("StudentsID");

                    b.ToTable("CourseStudent");

                    b.HasData(
                        new
                        {
                            CoursesID = 1,
                            StudentsID = 1
                        },
                        new
                        {
                            CoursesID = 2,
                            StudentsID = 1
                        },
                        new
                        {
                            CoursesID = 1,
                            StudentsID = 2
                        },
                        new
                        {
                            CoursesID = 2,
                            StudentsID = 3
                        },
                        new
                        {
                            CoursesID = 3,
                            StudentsID = 4
                        });
                });

            modelBuilder.Entity("ClassLibrary.Course", b =>
                {
                    b.HasOne("ClassLibrary.Lecturer", "Lecturer")
                        .WithMany("Courses")
                        .HasForeignKey("LecturerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.HasOne("ClassLibrary.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassLibrary.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClassLibrary.Lecturer", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
